/**
 * 基于 `sort-package-json` 4.0.0 默认规则的 `package.json` 顶层字段顺序。
 * `$schema` 按 JSON Schema 惯例补充在最前。
 *
 * @see {@link https://github.com/keithamus/sort-package-json/blob/v4.0.0/defaultRules.md | sort-package-json 4.0.0 默认规则}
 */
export const PACKAGE_JSON_FIELD_ORDER = [
  '$schema',
  'name',
  'displayName',
  'version',
  'stableVersion',
  'private',
  'description',
  'categories',
  'keywords',
  'homepage',
  'bugs',
  'repository',
  'funding',
  'license',
  'qna',
  'author',
  'maintainers',
  'contributors',
  'publisher',
  'sideEffects',
  'type',
  'imports',
  'exports',
  'main',
  'svelte',
  'umd:main',
  'jsdelivr',
  'unpkg',
  'module',
  'source',
  'jsnext:main',
  'browser',
  'react-native',
  'types',
  'typesVersions',
  'typings',
  'style',
  'example',
  'examplestyle',
  'assets',
  'bin',
  'man',
  'directories',
  'files',
  'workspaces',
  'binary',
  'scripts',
  'betterScripts',
  'wireit',
  'l10n',
  'contributes',
  'activationEvents',
  'husky',
  'simple-git-hooks',
  'pre-commit',
  'commitlint',
  'lint-staged',
  'nano-staged',
  'config',
  'nodemonConfig',
  'browserify',
  'babel',
  'browserslist',
  'xo',
  'prettier',
  'eslintConfig',
  'eslintIgnore',
  'npmpkgjsonlint',
  'npmPackageJsonLintConfig',
  'npmpackagejsonlint',
  'release',
  'remarkConfig',
  'stylelint',
  'ava',
  'jest',
  'jest-junit',
  'jest-stare',
  'mocha',
  'nyc',
  'c8',
  'tap',
  'oclif',
  'resolutions',
  'overrides',
  'dependencies',
  'devDependencies',
  'dependenciesMeta',
  'peerDependencies',
  'peerDependenciesMeta',
  'optionalDependencies',
  'bundledDependencies',
  'bundleDependencies',
  'extensionPack',
  'extensionDependencies',
  'flat',
  'packageManager',
  'engines',
  'engineStrict',
  'devEngines',
  'volta',
  'languageName',
  'os',
  'cpu',
  'preferGlobal',
  'publishConfig',
  'icon',
  'badges',
  'galleryBanner',
  'preview',
  'markdown',
  'pnpm',
] as const;

export const DIRECTORY_FIELD_ORDER = [
  'lib',
  'bin',
  'man',
  'doc',
  'example',
  'test',
] as const;

export const ESLINT_CONFIG_FIELD_ORDER = [
  'files',
  'excludedFiles',
  'env',
  'parser',
  'parserOptions',
  'settings',
  'plugins',
  'extends',
  'rules',
  'overrides',
  'globals',
  'processor',
  'noInlineConfig',
  'reportUnusedDisableDirectives',
] as const;

export const GIT_HOOK_ORDER = [
  'applypatch-msg',
  'pre-applypatch',
  'post-applypatch',
  'pre-commit',
  'pre-merge-commit',
  'prepare-commit-msg',
  'commit-msg',
  'post-commit',
  'pre-rebase',
  'post-checkout',
  'post-merge',
  'pre-push',
  'pre-receive',
  'update',
  'proc-receive',
  'post-receive',
  'post-update',
  'reference-transaction',
  'push-to-checkout',
  'pre-auto-gc',
  'post-rewrite',
  'sendemail-validate',
  'fsmonitor-watchman',
  'p4-changelist',
  'p4-prepare-changelist',
  'p4-post-changelist',
  'p4-pre-submit',
  'post-index-change',
] as const;

export const NPM_LIFECYCLE_SCRIPT_NAMES: ReadonlySet<string> = new Set([
  'install',
  'pack',
  'prepare',
  'publish',
  'restart',
  'shrinkwrap',
  'start',
  'stop',
  'test',
  'uninstall',
  'version',
]);

export const PNPM_CONFIG_FIELD_ORDER = [
  'peerDependencyRules',
  'neverBuiltDependencies',
  'onlyBuiltDependencies',
  'onlyBuiltDependenciesFile',
  'allowedDeprecatedVersions',
  'allowNonAppliedPatches',
  'updateConfig',
  'auditConfig',
  'requiredScripts',
  'supportedArchitectures',
  'overrides',
  'patchedDependencies',
  'packageExtensions',
] as const;

export const WIREIT_SCRIPT_FIELD_ORDER = [
  'command',
  'dependencies',
  'files',
  'output',
] as const;
